# -*- coding: utf-8 -*-
"""การจัดกลุ่มข่าวออนไลน์ด้วย TF-IDF และ K-Means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11BcQEjwujEeasr3NwCNFTto7I6l0BQRS
"""

!pip install kaggle

from google.colab import files
files.upload()

# ย้ายไฟล์ไปโฟลเดอร์ .kaggle และตั้ง permission
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# ดาวน์โหลด dataset BBC News Summary
!kaggle datasets download -d pariza/bbc-news-summary

# แตกไฟล์ zip
!unzip bbc-news-summary.zip -d bbc-news

import os
import pandas as pd
from glob import glob

# path ไปยังโฟลเดอร์ข่าว
base_path = "bbc-news/BBC News Summary/News Articles/"

data = []
categories = os.listdir(base_path)  # ['business','entertainment','politics','sport','tech']

for category in categories:
    folder_path = os.path.join(base_path, category)
    files = glob(os.path.join(folder_path, "*.txt"))
    for file in files:
        with open(file, "r", encoding="latin1") as f:  # ใช้ encoding latin1 เพื่อหลีกเลี่ยง error
            text = f.read()
            data.append([text, category])

# สร้าง DataFrame
df = pd.DataFrame(data, columns=["text", "category"])
print(df.head())
print(df["category"].value_counts())

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# 1. แปลงข้อความเป็นเวกเตอร์ด้วย TF-IDF
vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7, min_df=5)
X = vectorizer.fit_transform(df["text"])

from sklearn.cluster import KMeans

k = 5  # จำนวนหมวดข่าว
model = KMeans(n_clusters=k, random_state=42)
df["cluster"] = model.fit_predict(X)

# 3. แสดงผลลัพธ์ตัวอย่าง
print("ตัวอย่าง 10 ข่าว + หมวดจริง + Cluster ที่จัด:")
print(df[["text", "category", "cluster"]].head(10))

# 4. สรุปในแต่ละ cluster
for i in range(k): # ใช้ k แทน num_clusters
    print(f"\n=== Cluster {i} ===")
    sample = df[df.cluster == i].head(5)["text"].tolist()
    for s in sample:
        print("-", s[:200], "…")  # แสดง 200 ตัวอักษรแรก

# 5. Visualization ด้วย PCA 2D
pca = PCA(n_components=2)
points_2d = pca.fit_transform(X.toarray())  # ระวัง memory ถ้า dataset ใหญ่

plt.figure(figsize=(10, 8))
plt.scatter(points_2d[:, 0], points_2d[:, 1], c=df["cluster"], cmap="rainbow", alpha=0.6)
plt.title(
    "New Paradigms of Pattern Recognition\nNews Category Classification using TF-IDF and K-Means Clustering",
    fontsize=16
)

plt.show()

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# PCA 2D
pca = PCA(n_components=2)
points_2d = pca.fit_transform(X.toarray())

plt.figure(figsize=(10, 8))

# สีสำหรับ cluster
colors = ['red', 'green', 'blue', 'orange', 'purple']

for i in range(k):
    cluster_points = points_2d[df['cluster'] == i]
    plt.scatter(cluster_points[:, 0], cluster_points[:, 1],
                c=colors[i], label=f'Cluster {i}', alpha=0.6)

plt.title(
    "New Paradigms of Pattern Recognition\nNews Category Classification using TF-IDF and K-Means Clustering",
    fontsize=16
)

plt.legend()
plt.show()

"""**ดังนั้นจุดแต่ละสี (cluster) ที่เรา plot ใน PCA**

**สีแดง (Cluster 0) → ส่วนใหญ่เป็นธุรกิจและการเมือง**

**สีเขียว (Cluster 1) → ส่วนใหญ่เป็นกีฬา**

**สีน้ำเงิน (Cluster 2) → ส่วนใหญ่เป็นเทคโนโลยี**

**สีส้ม   (Cluster 3) → ส่วนใหญ่เป็นการบันเทิง**

**สีม่วง  (Cluster 4) → ส่วนใหญ่เป็นเทคโนโลยี**


"""

# สร้างตาราง cross-tab
ct = pd.crosstab(df['cluster'], df['category'])
print(ct)

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import seaborn as sns

# ใช้ t-SNE เพื่อกระจายจุดให้ออกห่างกันมากขึ้น (แทน PCA)
tsne = TSNE(n_components=2, random_state=42, perplexity=40, n_iter=1000)
X_embedded = tsne.fit_transform(X.toarray())

# เพิ่มข้อมูลตำแหน่ง t-SNE ลงใน DataFrame
df["tsne-2d-one"] = X_embedded[:, 0]
df["tsne-2d-two"] = X_embedded[:, 1]

# วาดกราฟ scatter โดยใช้สีแทน cluster
plt.figure(figsize=(12, 8))
sns.scatterplot(
    x="tsne-2d-one", y="tsne-2d-two",
    hue="cluster",
    palette="tab10",
    data=df,
    legend="full",
    alpha=0.7,
    s=70
)

# เปลี่ยนชื่อกราฟให้ตรงกับหัวข้อโปรเจกต์
plt.title(
    "New Paradigms of Pattern Recognition\nNews Category Classification using TF-IDF and K-Means Clustering",
    fontsize=16
)

plt.xlabel("t-SNE Dimension 1")
plt.ylabel("t-SNE Dimension 2")
plt.show()

"""**ดังนั้นจุดแต่ละสี (cluster) ที่เรา plot ใน PCA**

**สีแดง (Cluster 0) → ส่วนใหญ่เป็นธุรกิจและการเมือง**

**สีเขียว (Cluster 1) → ส่วนใหญ่เป็นกีฬา**

**สีน้ำเงิน (Cluster 2) → ส่วนใหญ่เป็นเทคโนโลยี**

**สีส้ม   (Cluster 3) → ส่วนใหญ่เป็นการบันเทิง**

**สีม่วง  (Cluster 4) → ส่วนใหญ่เป็นเทคโนโลยี**


"""

# สร้างตาราง cross-tab
ct = pd.crosstab(df['cluster'], df['category'])
print(ct)